name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Prisma client
        run: yarn prisma generate

      - name: Lint
        run: yarn lint

      - name: Type-check
        run: yarn type-check

      - name: Test
        run: yarn test
